### ISSUE TITLE
select_targets and git_version for installed copies

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#123]
select_targets fails on installed copies of the code with:
```
Traceback (most recent call last):
  File "/global/common/edison/contrib/desi/code/desitarget/0.8.0/bin/select_targets", line 4, in <module>
    __import__('pkg_resources').run_script('desitarget==0.8.0', 'select_targets')
  File "/global/common/edison/contrib/desi/conda/conda_3.5-20160913/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 719, in run_script
  File "/global/common/edison/contrib/desi/conda/conda_3.5-20160913/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 1504, in run_script
  File "/global/common/edison/contrib/desi/code/desitarget/0.8.0/lib/python3.5/site-packages/desitarget-0.8.0-py3.5.egg/EGG-INFO/scripts/select_targets", line 46, in <module>
    io.write_targets(ns.dest, targets, indir=ns.src, qso_selection=ns.qsoselection)
  File "/global/common/edison/contrib/desi/code/desitarget/0.8.0/lib/python3.5/site-packages/desitarget-0.8.0-py3.5.egg/desitarget/io.py", line 122, in write_targets
    depend.setdep(hdr, 'desitarget-git', gitversion().decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```
Fix then tag 0.8.1 and rerun select_targets.

**Comment by sbailey** [comment]
I fixed this directly in master and retagged as 0.8.1.  Closing ticket.
