### ISSUE TITLE
run_target_qa requires that $DISPLAY is set

### ISSUE THREAD

**Issue by dkirkby** [desihub/desitarget#240]
I used the following steps to generate target QA plots on cori:
```
source /project/projectdirs/desi/software/desi_environment.sh 17.9
run_target_qa /project/projectdirs/desi/target/catalogs/targets-dr5-0.16.2.fits \
   /project/projectdirs/desi/www/users/dkirkby/target_qa
```
However, this fails unless I have `$DISPLAY` set, with:
```
INFO:QA.py:1660:make_qa_plots: Assigned weights to pixels based on DESI footprint...t = 51.3s
Traceback (most recent call last):
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desitarget/0.15.0/bin/run_target_qa", line 4, in <module>
    __import__('pkg_resources').run_script('desitarget==0.15.0', 'run_target_qa')
...
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 144, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
```
The solution might be as simple as adding these lines to the top of the script (but I haven't tested this):
```
import matplotlib
matplotlib.use('Agg') # Must be before importing matplotlib.pyplot or pylab!
```

**Comment by geordie666** [comment]
Thanks, @dkirkby, the `matplotlib.use('Agg')` worked for me on cori.

Closed in https://github.com/desihub/desitarget/pull/245
