### ISSUE TITLE
generating bright star mask from DR 5

### ISSUE THREAD

**Issue by mehdirezaie** [desihub/desitarget#257]
Hi!

I have been trying to execute `select_target` (from desitarget 0.14 /global/project/projectdirs/desi/software/desi_environment.sh) on a single DR5 sweep file (as  a test, before I run it over the entire files). I am getting the following error. 

```
Traceback (most recent call last):
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desitarget/0.14.0/bin/select_targets", line 4, in <module>
    __import__('pkg_resources').run_script('desitarget==0.14.0', 'select_targets')
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desitarget/0.14.0/lib/python3.5/site-packages/desitarget-0.14.0-py3.5.egg/EGG-INFO/scripts/select_targets", line 55, in <module>
    qso_selection=ns.qsoselection, sandboxcuts=ns.sandbox, nside=nside)
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desitarget/0.14.0/lib/python3.5/site-packages/desitarget-0.14.0-py3.5.egg/desitarget/io.py", line 297, in write_targets
    photsys = release_to_photsys(data["RELEASE"])
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desitarget/0.14.0/lib/python3.5/site-packages/desitarget-0.14.0-py3.5.egg/desitarget/io.py", line 247, in release_to_photsys
    return r2p[release]
IndexError: index 5000 is out of bounds for axis 0 with size 4001
``` 

I think it is because I am using a relatively old version of desitarget with `releasedict = {3000: 'S', 4000: 'N'}` whereas I see in the master branch it is upgraded to `releasedict = {3000: 'S', 4000: 'N', 5000: 'S'}`.

Is there any way around this so I could still use the NERSC desitarget on DR 5? or do I have to wait until the desitarget is updated on Nersc?

Thanks so much
Mehdi

**Comment by moustakas** [comment]
@mehdirezaie -- executing
```
source /project/projectdirs/desi/software/desi_environment.sh 17.12
```
after logging onto NERSC should get you the latest stable software stack.  See the message from @geordie666 in [desi-data 3241] for more details, in case that's helpful.

**Comment by mehdirezaie** [comment]
@moustakas thanks so much! I am going to close this.
