### ISSUE TITLE
Error in ReadUniformSky 

### ISSUE THREAD

**Issue by apcooper** [desihub/desitarget#317]
Running `select_mock_targets` locally (i.e. not at NERSC) I get this error:
```
INFO:build.py:559:targets_truth: Working on target class: SKY
INFO:build.py:149:read_mock: Target: SKY, format: uniformsky, mockfile: /gpfs/data/DESI/mocks/uniformsky/0.1/uniformsky-2048-0.1.fits
INFO:mockmaker.py:845:readmock: Using cached coordinates, healpixels, and pixel weights from /gpfs/data/DESI/mocks/uniformsky/0.1/uniformsky-2048-0.1.fits
Traceback (most recent call last):
  File "/gpfs/data/DESI/software/modules/desitarget/32ac18d/bin/select_mock_targets", line 4, in <module>
    __import__('pkg_resources').run_script('desitarget==0.20.1.dev1661', 'select_mock_targets')
  File "/gpfs/data/dph3apc/anaconda/3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 719, in run_script
  File "/gpfs/data/dph3apc/anaconda/3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 1504, in run_script
  File "/gpfs/data/DESI/software/modules/desitarget/32ac18d/lib/python3.5/site-packages/desitarget-0.20.1.dev1661-py3.5.egg/EGG-INFO/scripts/select_mock_targets", line 108, in <module>
    no_spectra=args.no_spectra)
  File "/gpfs/data/DESI/software/modules/desitarget/32ac18d/lib/python3.5/site-packages/desitarget-0.20.1.dev1661-py3.5.egg/desitarget/mock/build.py", line 564, in targets_truth
    MakeMock=AllMakeMock[ii])
  File "/gpfs/data/DESI/software/modules/desitarget/32ac18d/lib/python3.5/site-packages/desitarget-0.20.1.dev1661-py3.5.egg/desitarget/mock/build.py", line 160, in read_mock
    dust_dir=dust_dir, mock_density=mock_density)
  File "/gpfs/data/DESI/software/modules/desitarget/32ac18d/lib/python3.5/site-packages/desitarget-0.20.1.dev1661-py3.5.egg/desitarget/mock/mockmaker.py", line 3928, in read
    mock_density=mock_density)
  File "/gpfs/data/DESI/software/modules/desitarget/32ac18d/lib/python3.5/site-packages/desitarget-0.20.1.dev1661-py3.5.egg/desitarget/mock/mockmaker.py", line 846, in readmock
    _, _, ra, dec, allpix, pixweight = ReadGaussianField.cached_radec
TypeError: 'NoneType' object is not iterable
```

My hunch is that the last line (846) should be `_, _, ra, dec, allpix, pixweight = ReadUniformSky.cached_radec`. 

@moustakas, can you advise?

**Comment by moustakas** [comment]
Fixed in #318
