### ISSUE TITLE
select_mock_targets crash on lya_forest/london/v4.2.0/master.fits: column name 'Z' not found

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#571]
I could use help with this, though I don't have it in a trivial-to-reproduce state yet:

Using desitarget master:
```
srun -A desi -N 6 -n 46 -c 8 -C haswell -t 01:00:00 --qos interactive mpi_select_mock_targets \
  --output_dir /global/cscratch1/sd/sjbailey/minitest-19.11/targets \
  --config /global/cscratch1/sd/sjbailey/minitest-19.11/targets/select-mock-targets.yaml \
  --seed 1 --nproc 4 --nside 64 \
  --tiles /global/cscratch1/sd/sjbailey/minitest-19.11/survey/test-tiles.fits
```
logging to `/global/cscratch1/sd/sjbailey/minitest-19.11/targets/select_mock_targets.log`, fails with

```
ERROR:mpi_select_mock_targets:181:<module>: Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/mock/mockmaker.py", line 2176, in readmock
    upper=True, ext=1)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 101, in read
    data = fits[item].read(**keys)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 1813, in read
    data = self.read_columns(columns, **keys)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 2021, in read_columns
    self._FITS.read_columns_as_rec(self._ext+1, colnumsp, array, rows)
OSError: FITSIO status = 108: error reading from FITS file
Error reading data buffer from file:
/global/project/projectdirs/desi/mocks/lya_forest/london/v4.2.0/master.fits


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 2630, in _extract_colnum
    colnum = self._colnames_lower.index(colstr.lower())
ValueError: 'z' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/bin/mpi_select_mock_targets", line 172, in <module>
    survey=args.survey)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/mock/build.py", line 903, in targets_truth
    MakeMock=AllMakeMock[ii], dndz=dndz)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/mock/build.py", line 174, in read_mock
    nside_galaxia=nside_galaxia, mock_density=mock_density)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/mock/mockmaker.py", line 3270, in read
    only_coords=only_coords, seed=self.seed)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/mock/mockmaker.py", line 2181, in readmock
    upper=True, ext=1)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 101, in read
    data = fits[item].read(**keys)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 1813, in read
    data = self.read_columns(columns, **keys)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 1995, in read_columns
    colnums = self._extract_colnums(columns)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 2607, in _extract_colnums
    colnums[i] = self._extract_colnum(columns[i])
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 2632, in _extract_colnum
    raise ValueError(mess)
ValueError: column name 'Z' not found (case insensitive)
```

Indeed, it looks like the columns are named "Z_QSO_RSD" and "Z_QSO_NO_RSD", though I haven't found an earlier version of the mocks with a different name.  When I tried to run `select_mock_targets` by itself with the same input config file, it didn't complain.  This is blocking integration testing with the minitest notebook.  Punting to @moustakas or others for help.  Thanks.

**Comment by moustakas** [comment]
I'll take this.

**Comment by moustakas** [comment]
Can you fix permissions?
```
ioannis@cori11:~% cat /global/cscratch1/sd/sjbailey/minitest-19.11/targets/select-mock-targets.yaml
cat: /global/cscratch1/sd/sjbailey/minitest-19.11/targets/select-mock-targets.yaml: Permission denied
```
But regardless I wonder if this was an intermittent I/O problem.  The crash was in this code block, which was originally written to support very early versions of the CoLoRe mocks:
```
        try: # new data model
            tmp = fitsio.read(mockfile, columns=['RA', 'DEC', 'MOCKID', 'Z_QSO_RSD',
                                                 'Z_QSO_NO_RSD', 'PIXNUM'],
                              upper=True, ext=1)
            zz = tmp['Z_QSO_RSD'].astype('f4')
            zz_norsd = tmp['Z_QSO_NO_RSD'].astype('f4')
        except: # old data model
            tmp = fitsio.read(mockfile, columns=['RA', 'DEC', 'MOCKID' ,'Z', 'PIXNUM'],
                              upper=True, ext=1)
            zz = tmp['Z'].astype('f4')
            zz_norsd = tmp['Z'].astype('f4')
```
The file it's trying to read, however, 
```
/global/project/projectdirs/desi/mocks/lya_forest/london/v4.2.0/master.fits
```
has the columns the code expects, to wit
```
In [7]: fitsio.FITS('/global/project/projectdirs/desi/mocks/lya_forest/london/v4.2.0/master.fits')[1]         
Out[7]: 

  file: /global/project/projectdirs/desi/mocks/lya_forest/london/v4.2.0/master.fits
  extension: 1
  type: BINARY_TBL
  extname: CATALOG
  rows: 7463972
  column info:
    RA                  f8  
    DEC                 f8  
    Z_QSO_NO_RSD        f8  
    Z_QSO_RSD           f8  
    MOCKID              i8  
    PIXNUM              i8  
    FILENUM             i8  
```
So my only explanation is that the `master.fits` file couldn't be accessed at the time you ran the code...

If you unveil the `.yaml` file and update the desitarget tag (to include the #568 fix) then I can try to isolate and reproduce this crash.

**Comment by sbailey** [comment]
Sorry about the permissions; that was a side effect of copying it from /global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/mock/data/select-mock-targets.yaml .

This was run with current desitarget master (post-#568 fix) and the desitarget as-provided select-mock-targets.yaml .  Intermittent I/O problem would also be consistent with why I wasn't able to reproduce it with a single select_mock_targets call for a single healpixel.  I'll try the big test again (though you may not get the answer until tomorrow...).

**Comment by sbailey** [comment]
Yep, indeed, on rerun with same code and same inputs it worked fine.  Transient I/O failure.  I'll report a ticket to NERSC instead of desitarget.  Closing.
