### ISSUE TITLE
problem using fiberassign on dr9d SV data

### ISSUE THREAD

**Issue by forero** [desihub/desitarget#583]
I tried to run fiberassing on a dr9d sv file using

```
fiberassign --mtl /project/projectdirs/desi/target/catalogs/dr9d/PRnone/targets/sv/resolve/bright/sv1-targets-dr9-hp-X.fits --sky sky_gama_g12.fits --footprint tiles_gama_g12.fits --outdir output --overwrite 
```

and it failed with

```
INFO: Loaded focalplane for time stamp 2020-02-06 21:19:00.203983
INFO: Focalplane has 0 fibers that are stuck / broken
INFO: Target file /project/projectdirs/desi/target/catalogs/dr9d/PRnone/targets/sv/resolve/bright/sv1-targets-dr9-hp-X.fits has 4089992 rows.  Reading in chunks of 1000000
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/master/bin/fiberassign", line 151, in <module>
    run_assign_full(assign_args)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/master/py/fiberassign/scripts/assign.py", line 330, in run_assign_full
    hw, tiles, tgs = run_assign_init(args)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/master/py/fiberassign/scripts/assign.py", line 296, in run_assign_init
    excludemask=args.excludemask)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/master/py/fiberassign/targets.py", line 790, in load_target_file
    excludemask=excludemask)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/master/py/fiberassign/targets.py", line 640, in load_target_table
    fsafemask, fexcludemask = default_target_masks(tgdata)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/master/py/fiberassign/targets.py", line 434, in default_target_masks
    default_survey_target_masks(filesurvey)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/master/py/fiberassign/targets.py", line 402, in default_survey_target_masks
    sciencemask = default_sv1_sciencemask()
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/master/py/fiberassign/targets.py", line 126, in default_sv1_sciencemask
    sciencemask |= sv1_mask['MWS_WD_SV']
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desiutil/master/py/desiutil/bitmask.py", line 142, in __getitem__
    return self._bits[bitname]
KeyError: 'MWS_WD_SV'
```

is it a fiberassign problem? is it a problem with the target file?

The same command works fine with the files for the `main` survey.

**Comment by geordie666** [comment]
This appears to be an issue with `fiberassign`, not `desitarget`.

Here:

https://github.com/desihub/fiberassign/blob/481bb5770871239ee375bea58a5ef41a06105747/py/fiberassign/targets.py#L23

`fiberassign` imports the primary mask:
```
from desitarget.sv1.sv1_targetmask import desi_mask as sv1_mask
```
But, here:

https://github.com/desihub/fiberassign/blob/481bb5770871239ee375bea58a5ef41a06105747/py/fiberassign/targets.py#L126

`fiberassign` checks the primary mask against `MWS_WD_SV`, a bit-name that only appears in the _secondary_ mask. This means that the correct mask to import would be:

```
from desitarget.sv1.sv1_targetmask import scnd_mask as sv1_mask
```

I suggest closing this issue and opening a corresponding issue in the `fiberassign` repo.

**Comment by forero** [comment]
Thanks @geordie666. I will open the issue over there.
