### ISSUE TITLE
mpi_select_mock_targets crashes due to wrong use of `refcat`

### ISSUE THREAD

**Issue by forero** [desihub/desitarget#585]
We are having problems runnig `mpi_select_mock_targets` from the tutorials repo.

This is the error message:

```
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/internal/sharedmem.py", line 265, in _slaveMain
    self.main(self, *self.args)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/internal/sharedmem.py", line 563, in _main
    r = realfunc(work)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/internal/sharedmem.py", line 629, in realfunc
    else: return func(i)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/cuts.py", line 1003, in isBGS
    south=south, targtype=targtype)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/cuts.py", line 1119, in isBGS_lslga
    LX = np.array([rc[0] == "L" for rc in refcat], dtype=bool)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/cuts.py", line 1119, in <listcomp>
    LX = np.array([rc[0] == "L" for rc in refcat], dtype=bool)
IndexError: string index out of range
```

It looks like this is a problem using `refcat` introduced here https://github.com/desihub/desitarget/commit/90467034bf1bb73f7721b461c2eb6b1a203350df

This is the issue in the tutorials repo with some other comments https://github.com/desihub/tutorials/issues/33#issuecomment-584706807

**Comment by geordie666** [comment]
Addressed in #588.
