### ISSUE TITLE
select_mock_targets crash ValueError: unsupported type 'U20'

### ISSUE THREAD

**Issue by sbailey** [desihub/desitarget#603]
@moustakas do you recognize this?  It looks like another fitsio 9.x vs. 1.x bytes vs. unicode strings thing.  It's crashing the minitest on master.

Using py/desitarget/mock/data/select-mock-targets.yaml with command
```
srun -A desi -N 4 -n 26 -c 8 -C haswell -t 01:00:00 --qos interactive \
mpi_select_mock_targets \
--output_dir /global/cscratch1/sd/sjbailey/minitest-20.3/targets \
--config /global/cscratch1/sd/sjbailey/minitest-20.3/targets/select-mock-targets.yaml \
--seed 1 --nproc 4 --nside 64 \
--tiles /global/cscratch1/sd/sjbailey/minitest-20.3/survey/test-tiles.fits
```
See logs in /global/cscratch1/sd/sjbailey/minitest-20.3/targets/select_mock_targets.log

```
INFO:mpi_select_mock_targets:162:<module>: Calling targets_truth() with the following options
INFO:mpi_select_mock_targets:163:<module>:   output_dir /global/cscratch1/sd/sjbailey/minitest-20.3/targets
INFO:mpi_select_mock_targets:164:<module>:   seed       1666063943
INFO:mpi_select_mock_targets:165:<module>:   nside      64
INFO:mpi_select_mock_targets:166:<module>:   nproc      4
INFO:mpi_select_mock_targets:167:<module>:   verbose    False
INFO:mpi_select_mock_targets:168:<module>:   healpixels [5295]
...
ERROR:mpi_select_mock_targets:178:<module>: Pixels [5295] failed after 26.2 minutes
ERROR:mpi_select_mock_targets:181:<module>: Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/bin/mpi_select_mock_targets", line 172, in <module>
    survey=args.survey)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/mock/build.py", line 981, in targets_truth
    qso_selection='colorcuts', mockdata=mockdata)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/io.py", line 582, in write_targets
    extname='TRUTH_{}'.format(obj))
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 253, in write
    **keys)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 486, in write
    table_type=table_type)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 767, in write_table
    table_type=table_type)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 863, in create_table_hdu
    names, formats, dims = array2tabledef(data, table_type=table_type)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 3482, in array2tabledef
    name, form, dim = npy2fits(d,table_type=table_type)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 3641, in npy2fits
    name, form, dim = npy_num2fits(d, table_type=table_type)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 3667, in npy_num2fits
    raise ValueError("unsupported type '%s'" % npy_dtype)
ValueError: unsupported type 'U20'
```

**Comment by sbailey** [comment]
For easier (?) debugging, this problem is caught by the test_mock_build unit test at NERSC.  We don't run that on Travis because it requires such large inputs and takes so long, but the nightly unit tests caught it last night:
```
======================================================================
ERROR: test_targets_truth (desitarget.test.test_mock_build.TestMockBuild)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/test/test_mock_build.py", line 43, in test_targets_truth
    targets_truth(params, healpixels=[99737,], nside=256, output_dir=self.outdir, no_spectra=True)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/mock/build.py", line 981, in targets_truth
    qso_selection='colorcuts', mockdata=mockdata)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desitarget/master/py/desitarget/io.py", line 582, in write_targets
    extname='TRUTH_{}'.format(obj))
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 253, in write
    **keys)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 486, in write
    table_type=table_type)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 767, in write_table
    table_type=table_type)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 863, in create_table_hdu
    names, formats, dims = array2tabledef(data, table_type=table_type)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 3482, in array2tabledef
    name, form, dim = npy2fits(d,table_type=table_type)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 3641, in npy2fits
    name, form, dim = npy_num2fits(d, table_type=table_type)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 3667, in npy_num2fits
    raise ValueError("unsupported type '%s'" % npy_dtype)
ValueError: unsupported type 'U20'
```

**Comment by moustakas** [comment]
Funnily enough, this crash appears to be due to the `TRANSIENTS_` columns which were added in https://github.com/desihub/desisim/pull/525.  @sybenzvi 

We also seem to be pinned at `fitsio/0.9.11`, but I think it's a known issue that we should try to upgrade to `1.0.6` ASAP.

**Comment by moustakas** [comment]
Done in #604.
