### ISSUE TITLE
mpi_select_mock_targets

### ISSUE THREAD

**Issue by zdplayground** [desihub/desitarget#745]
Hi,
Recently I tried to go through the notebook https://github.com/desihub/tutorials/blob/master/FiberAssignMocks.ipynb in NERSC. But it fails when running target selection for mtl file generation.
Here is the error:

ERROR:mpi_select_mock_targets:182:<module>: Pixels [4528] failed after 4.0 minutes
ERROR:mpi_select_mock_targets:185:<module>: Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desitarget/master/bin/mpi_select_mock_targets", line 173, in <module>
    targets_truth(params, output_dir=args.output_dir, seed=rankseeds[i],
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desitarget/master/py/desitarget/mock/build.py", line 905, in targets_truth
    data, MakeMock = read_mock(params['targets'][target_name], log, target_name,
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desitarget/master/py/desitarget/mock/build.py", line 172, in read_mock
    data = MakeMock.read(mockfile=mockfile, mockformat=mockformat,
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desitarget/master/py/desitarget/mock/mockmaker.py", line 3857, in read
    data = MockReader.readmock(mockfile, target_name=self.objtype,
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desitarget/master/py/desitarget/mock/mockmaker.py", line 1389, in readmock
    gmmout = self.sample_GMM(nobj, target=target_name, isouth=isouth,
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desitarget/master/py/desitarget/mock/mockmaker.py", line 669, in sample_GMM
    samp[south] = _samp_iterate(samp[south], target=target, south=True, rand=rand,
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desitarget/master/py/desitarget/mock/mockmaker.py", line 647, in _samp_iterate
    itarg = colorcuts_function(gflux=gflux, rflux=rflux, zflux=zflux,
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desitarget/master/py/desitarget/cuts.py", line 592, in isELG_colors
    gfib = 22.5 - 2.5*np.log10(gfiberflux.clip(1e-16))
AttributeError: 'NoneType' object has no attribute 'clip'

Could you give some suggestions to resolve this?

Thanks!

**Comment by geordie666** [comment]
@zdplayground: The mocks have fallen behind the code used for targeting on "real" data. In the short-term, this will remain the case. But we are planning to update the mocks to work with the Main Survey targeting code as soon as DESI operations are stable. You're not the only one who has noticed issues (see, e.g., https://github.com/desihub/desisim/issues/553#issuecomment-843610307). Apologies for the delay, but we have to prioritize getting DESI up-and-running for the next few weeks at least.

**Comment by moustakas** [comment]
Fixed in #788. @zdplayground please feel free to test and open a new ticket if there are any issues.
